# Circumference Calculation
# Write a program that calculates the circumference of 
# a wheel. The formula is C = 2πr,
# where π is the value 3.14 and r is 
# the radius of the circle.

# To take this a step further,
# let the radius of the circle be
# a random integer generated by the random module

import random
from math import sqrt, ceil

c = 2 * 3.14
print(c)

r = sqrt(c)
print(r)

d = ceil(r)
print(d)

random_number = random.randint(3, 10)
print(random_number)

